name: constellation-frontend-integration
on: [push]
jobs:
  Integration-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install packages
        run: npm install --force
      - name: Run Playwright tests
        run: npx playwright test
      - name: Run Jest tests
        run: npm run test
      - name: Bundle
        run: npm run build
